---
- hosts: all
  tasks:
  - name: "download rclone {{ rclone_release_zip_url | default('https://github.com/rclone/rclone/releases/download/v1.68.1/rclone-v1.68.1-linux-amd64.zip') }}"
    get_url: 
      url: "{{ rclone_release_zip_url | default('https://github.com/rclone/rclone/releases/download/v1.68.1/rclone-v1.68.1-linux-amd64.zip') }}"
      dest: /tmp/rclone.zip
      force: true
  - name: unarchive rclone
    unarchive:
      remote_src: true
      src: /tmp/rclone.zip
      dest: /tmp
  - name: find rclone bin path
    find:
      paths: /tmp
      patterns: 'rclone-*'
      file_type: directory
    register: rclone_bin_paths
  - name: backup 
    shell: 'curl -sL https://raw.githubusercontent.com/oopsdevops001/backup/refs/heads/main/backup.sh | sh'
    environment:
      PATH: "{{ rclone_bin_paths.files[0].path }}:{{ lookup('env','PATH') }}"
      TARGET: "{{ RCLONE_CONFIG_TARGET_NAME }}"
      SRC: "{{ RCLONE_CONFIG_SRC_NAME }}"
      BACKUP_NAME: "{{ RCLONE_BACKUP_NAME }}"
      PASSWORD: "{{ ARCHIVE_PASSWORD | "" }}"
