---
- hosts: all
  tasks:
  - name: "download rclone {{ rclone_release_zip_url | default('https://github.com/rclone/rclone/releases/download/v1.68.1/rclone-v1.68.1-linux-amd64.zip') }}"
    get_url: 
      url: "{{ rclone_release_zip_url | default('https://github.com/rclone/rclone/releases/download/v1.68.1/rclone-v1.68.1-linux-amd64.zip') }}"
      dest: /tmp/rclone.zip
      force: true
  - name: unarchive rclone
    unarchive:
      remote_src: true
      src: /tmp/rclone.zip
      dest: /tmp
    - name: find rclone bin path
      find:
        paths: /tmp
        patterns: 'rclone-*'
        file_type: directory
      register: rclone_bin_paths

    - name: backup 
      shell: 'echo $PATH'
      environment:
        PATH: {{ rclone_bin_paths[0].path }}
